services:
  - type: web
    name: curious-minds-future-toppers
    runtime: node
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: node .next/standalone/server.js
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: DATABASE_URL
        sync: false
